# NumPy & SciPy
This is a quick overview of NumPy & SciPy libraries.

# NumPy
NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

Reference: https://numpy.org/doc/stable/user/absolute_beginners.html#

## Importing NumPy

In [1]:
# numpy is the top package name, and “import numpy” doesn't import submodules like numpy.f2py
from numpy import *
# or 
from numpy import array
# or 
import numpy as np

## Finding Documentation

In [2]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
   polyval(p, x)
 

In [3]:
np.info(np.polyval)

 polyval(p, x)

Evaluate a polynomial at specific values.

.. note::
   This forms part of the old polynomial API. Since version 1.4, the
   new polynomial API defined in `numpy.polynomial` is preferred.
   A summary of the differences can be found in the
   :doc:`transition guide </reference/routines.polynomials>`.

If `p` is of length N, this function returns the value:

    ``p[0]*x**(N-1) + p[1]*x**(N-2) + ... + p[N-2]*x + p[N-1]``

If `x` is a sequence, then ``p(x)`` is returned for each element of ``x``.
If `x` is another polynomial then the composite polynomial ``p(x(t))``
is returned.

Parameters
----------
p : array_like or poly1d object
   1D array of polynomial coefficients (including coefficients equal
   to zero) from highest degree to the constant term, or an
   instance of poly1d.
x : array_like or poly1d object
   A number, an array of numbers, or an instance of poly1d, at
   which to evaluate `p`.

Returns
-------
values : ndarray or poly1d
   If `x` is a poly1d instan

## Arrays in NumPy

In [4]:
# Simple array
a = np.array([0,1,2,3])
print(a)
# Size
print('Size:', a.size)
# Shape
print('Shape:',a.shape)
# Ndim – number of dimension
print('Number of dimensions:', a.ndim)
# Type
print('Type:', type(a))
# Type of elements
print('Element type:', a.dtype)
# Bytes per element
print('Number of bytes per element:', a.itemsize)
# Number of bytes
print('Total number of bytes:', a.nbytes)

[0 1 2 3]
Size: 4
Shape: (4,)
Number of dimensions: 1
Type: <class 'numpy.ndarray'>
Element type: int32
Number of bytes per element: 4
Total number of bytes: 16


## Creating Arrays

In [5]:
# Creating an Array
a = np.array([1,2,3,4])
print(a)
# Creating an Array including float numbers
a = np.array([1, 4, 5, 8], float)
print(a)
# Checking types
print('Type:', type(a))

[1 2 3 4]
[1. 4. 5. 8.]
Type: <class 'numpy.ndarray'>


In [6]:
# numpy.arange([start,]stop,[step,]dtype=None)
print(np.arange(3))
print(np.arange(3.0))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[0. 1. 2.]
[3 4 5 6]
[3 5]


In [7]:
# numpy.linspace (start, stop, num=50, endpoint=True, retstep=False, dtype=None)
print(np.linspace(2.0, 3.0, num=5))
print(np.linspace(2.0, 3.0, num=5, endpoint=False))
print(np.linspace(2.0, 3.0, num=5, retstep=True))

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


## Operations on Arrays

In [8]:
# Simple Operations on Arrays
a = np.array([1,2,3,4])
b = a + a
b

array([2, 4, 6, 8])

In [9]:
c = a * a
c

array([ 1,  4,  9, 16])

In [10]:
d = a ** a
d

array([  1,   4,  27, 256])

In [11]:
# Simple Math Functions
x = 2
y = x + a
y

array([3, 4, 5, 6])

In [12]:
y = x * a
y

array([2, 4, 6, 8])

In [13]:
y = sin(a)
y

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [14]:
# NumPy defines PI and e constants
print(pi)
print(e)

3.141592653589793
2.718281828459045


In [15]:
a = np.array([1,2,3,4])
c = (2 * pi) * a
c

array([ 6.28318531, 12.56637061, 18.84955592, 25.13274123])

In [16]:
y = sin(c)
y

array([-2.44929360e-16, -4.89858720e-16, -7.34788079e-16, -9.79717439e-16])

In [17]:
# In-place operations
x = arange(6)
z = 2 * pi
x = (x * z).astype(int32)
x

array([ 0,  6, 12, 18, 25, 31])

In [18]:
# On Float Elements
x = np.arange(6.)
x *= z
x

array([ 0.        ,  6.28318531, 12.56637061, 18.84955592, 25.13274123,
       31.41592654])

## Setting Array Elements – Filling Arrays

In [19]:
# Indexing
a = array([1,2,3,4])
a[0]

1

In [20]:
# Setting values
a[0] = 2 * pi
a[0]

6

In [21]:
a

array([6, 2, 3, 4])

In [22]:
# Fill - Fill the array with a scalar value
a.fill(0)
a

array([0, 0, 0, 0])

In [23]:
# Assigning a float into a Integer array
a[0]=2.34
a

array([2, 0, 0, 0])

In [24]:
a.fill(2.3)
a

array([2, 2, 2, 2])

In [25]:
# Filling by using slice
a[:]=1
a

array([1, 1, 1, 1])

## Slicing Arrays
Slicing can extract a portion of an array by using a lower and upper bound.
var[start:end:step]: This notation indicates that elements from index start (inclusive) up to index end (exclusive) will be included in the result

In [26]:
a = array([3,21,1,6,7])
a[1:3]

array([21,  1])

In [27]:
# Negative Indexes
a[1:-2]

array([21,  1])

In [28]:
a[-3:-1]

array([1, 6])

In [29]:
# Omitting indices: start or end or both
a[:2]

array([ 3, 21])

In [30]:
a[-2:]

array([6, 7])

In [31]:
# Slicing with steps
a[::2] # elements with even indices

array([3, 1, 7])

In [32]:
a[1::2] # elements with odd indices

array([21,  6])

In [33]:
# Slices are References
a = array([1,2,3,4,5])
b = a[2:4]
b

array([3, 4])

In [34]:
b[0] = 100
a

array([  1,   2, 100,   4,   5])

## N-Dimensional Arrays

In [35]:
# A 2-D array
b = array([[ 10, 11, 12, 13], [20, 21, 22, 23] ])
b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [36]:
# Shape, size, ndim
print(b.shape)
print(b.size)
print(b.ndim)

(2, 4)
8
2


In [37]:
# Indexing in 2-D
b[1,3]

23

In [38]:
# Setting Values
b[1,3] = 2.3
b

array([[10, 11, 12, 13],
       [20, 21, 22,  2]])

In [39]:
# Addressing the rows using single index
b[1]

array([20, 21, 22,  2])

## Multidimensional Array Slicing

In [40]:
# Similar to 1-D
c = array([[ 10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33], [40, 41, 42, 43]])
c[1:3]

array([[20, 21, 22, 23],
       [30, 31, 32, 33]])

In [41]:
# Addressing a column
c[:,2]

array([12, 22, 32, 42])

In [42]:
# With steps
c[2::2,::2]

array([[30, 32]])

## Advanced indexing

In [43]:
# Indexing by using positions
a = arange(10,40,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [44]:
indices = array([1,3,-4])
x = a[indices]
x

array([12, 16, 32])

In [45]:
# Indexing with Booleans
a = array([ 10, 11, 12, 13, 14])
mymask = array([1,0,1,1,1],dtype=bool)
y = a[mymask]
y

array([10, 12, 13, 14])

In [46]:
# Create a mask by condition
mymask2 = a < 13
mymask2

array([ True,  True,  True, False, False])

In [47]:
y = a[mymask2]
y

array([10, 11, 12])

## Where Method - Finding Indexes

In [48]:
# Where: finds indexes in array where expression is True
a = array([1.19, 2.42, 3.91, 4.66])
a > 2

array([False,  True,  True,  True])

In [49]:
 where(a > 2) 

(array([1, 2, 3], dtype=int64),)

In [50]:
# Where 2D
a = array([[0, 1, 2, 3],
           [4, 5, 6, 7]])
a > 2

array([[False, False, False,  True],
       [ True,  True,  True,  True]])

In [51]:
mindex = where(a > 2)
mindex

(array([0, 1, 1, 1, 1], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [52]:
y = a[mindex]
y

array([3, 4, 5, 6, 7])

## Reshaping Arrays

In [53]:
# Arrays can be reshaped
a = arange(10)
a.shape

(10,)

In [54]:
a.shape = (2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
# Dimension - 1
a.shape = (2, 1, 5)
a

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [56]:
# Reshape – Returns a new array from the original array
b = a.reshape(5, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [57]:
# Reshape do not remove elements
# E.g., a.reshape(3, 3)

## Flatten Arrays and Flat Attribute

In [58]:
# Flatten() - Converts Multidimensional arrays into one dimensional array
a = array([[0, 1],
[2, 3],
[4, 5],
[6, 7],
[8, 9]])
b = a.flatten()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# a.ravel() is the same as a.flatten(), but works a reference on the original array
b = a.ravel()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b[1] = 100
a

array([[  0, 100],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [61]:
# Attribute – flat is an attribute that can be used like an iterator to access elements in a N-D array as one dimensional array
b = a.flat
b[2] = 200
a

array([[  0, 100],
       [200,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

## Array Transpose

In [62]:
## Transpose
a = array([[0, 1, 2, 3, 4],
           [5, 6, 7, 8, 9]])
a.transpose() 

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [63]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [64]:
# Strides are Tuple of bytes to step in each dimension, 4 bytes (1 value) to move to the next column, but 20 bytes 
# (5 values) to get to the same position in the next row. Transpose only changes the values of "Strides" in the array memory
a.strides

(20, 4)

In [65]:
a.T.strides

(4, 20)

## Array Calculation Methods

In [66]:
# Sum – sum up the elements
a = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
sum(a)

45

In [67]:
# Sum along the axis
a = array([[0, 1], 
[2, 3],
[4, 5],
[6, 7],
[8, 9]])

sum(a, axis = 0)

array([20, 25])

In [68]:
sum(a, axis = 1)

array([ 1,  5,  9, 13, 17])

In [69]:
# Product – calculate product of columns
a.prod(axis = 0)

array([  0, 945])

In [70]:
a.prod(axis = 1)

array([ 0,  6, 20, 42, 72])

## Min/Max

In [71]:
# Min – Find the minimum. max for maximum
a = array([[0, 1, 2, 3, 4],
          [5, 6, 7, 8, 9]])
a.min(axis = 0) 

array([0, 1, 2, 3, 4])

In [72]:
a.min(axis = 1)

array([0, 5])

In [73]:
# argmin – finding the index of Minimum element. argmax for max
a.argmin(axis = 1)

array([0, 0], dtype=int64)

In [74]:
a.argmin(axis = 0)

array([0, 0, 0, 0, 0], dtype=int64)

In [75]:
# Diagonal - Extract the diagonal from array
a = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
a.diagonal()

array([1, 5, 9])

## Statistics Array Methods

In [76]:
# Mean
a = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
a.mean(axis = 0)

array([4., 5., 6.])

In [77]:
# Average
average(a, axis = 0)

array([4., 5., 6.])

In [78]:
# Average with weights
average(a, weights = [1, 2, 4], axis = 0) 

array([5.28571429, 6.28571429, 7.28571429])

In [79]:
# Standard Deviation
a.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [80]:
# Variance
a.var(axis = 0) 

array([6., 6., 6.])

## Other Useful Array Methods

In [81]:
# Clip – limit the values in an array
a = array([20, 21, 22, 23, 24, 25, 26, 27, 28])
# set values less than 22 to 22 and bigger than 27 to 27
a.clip(22, 27)

array([22, 22, 22, 23, 24, 25, 26, 27, 27])

In [82]:
# Peak to Peak - Range of values (maximum - minimum) along an axis
a.ptp(axis = 0)

8

In [83]:
# Rounding Float Numbers
a = array([1.19, 2.42, 3.91, 4.66])
a.round()

array([1., 2., 4., 5.])

In [84]:
a.round(decimals = 1)

array([1.2, 2.4, 3.9, 4.7])

# SciPy
SciPy is a collection of mathematical algorithms and convenience functions built on NumPy . It adds significant power to Python by providing the user with high-level commands and classes for manipulating and visualizing data.

Important subpackages:
- linalg: Linear algebra
- sparse: Sparse matricies and associated routines
- stats: Statistical distributions and functions

Reference: https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide

## scipy.linalg
Functions related to Linear Algebra
Basic routines:
- Finding Inverse - linalg.inv
- Solving linear system - linalg.solve 
- Finding Determinant - linalg.det 
- Computing norms - linalg.norm

Reference: https://docs.scipy.org/doc/scipy/reference/linalg.html

### Inverse of a Matrix
scipy.linalg.inv(a, overwrite_a=False, check_finite=True)

In [85]:
import numpy as np
from scipy import linalg
a = np.array([[1., 2.], [3., 4.]])
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [86]:
a.dot(linalg.inv(a)) 

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

### Solve the linear equation 
scipy.linalg.solve(a, b, lower=False, overwrite_a=False, overwrite_b=False, check_finite=True, assume_a='gen', transposed=False)
set a @ x == b for the unknown x for square a matrix

In [87]:
import numpy as np
from scipy import linalg
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
x = linalg.solve(a, b)
x

array([ 2., -2.,  9.])

In [88]:
np.dot(a, x) == b

array([ True,  True,  True])

## Sparse matrices (scipy.sparse)
SciPy 2-D sparse array package for numeric data

Sparse matrix classes
- bsr_matrix(arg1[, shape, dtype, copy, blocksize]) Block Sparse Row matrix. 
- coo_matrix(arg1[, shape, dtype, copy]) A sparse matrix in COOrdinate format. 
- csc_matrix(arg1[, shape, dtype, copy]) Compressed Sparse Column matrix. 
- csr_matrix(arg1[, shape, dtype, copy]) Compressed Sparse Row matrix. 
- dia_matrix(arg1[, shape, dtype, copy]) Sparse matrix with DIAgonal storage.
- dok_matrix(arg1[, shape, dtype, copy]) Dictionary Of Keys based sparse matrix.
- lil_matrix(arg1[, shape, dtype, copy]) Row-based linked list sparse matrix.
- spmatrix([maxprint]) This class provides a base class for all sparse matrices.

Reference: https://docs.scipy.org/doc/scipy/reference/sparse.html

### Compressed Sparse Column matrix
class scipy.sparse.csc_matrix(arg1, shape=None, dtype=None, copy=False)

In [89]:
import numpy as np
from scipy.sparse import csc_matrix
csc_matrix((3, 4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [90]:
row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
csc_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]], dtype=int32)

## Statistics (scipy.stats)
A large number of probability distributions as well as a growing library of statistical functions

Distributions like: norm, bernoulli, poisson

Statistical functions like:
- stats: Return mean, variance 
- PDF: Probability Density Function
- PPF: Percent Point Function (Inverse of CDF)

Reference: https://docs.scipy.org/doc/scipy/reference/stats.html

# SciPy
SciPy is a collection of mathematical algorithms and convenience functions built on NumPy . It adds significant power to Python by providing the user with high-level commands and classes for manipulating and visualizing data.

Important subpackages:
- linalg: Linear algebra
- sparse: Sparse matricies and associated routines
- stats: Statistical distributions and functions

Reference: https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide